export const EVENT_INPUT_CHANGE = "EVENT_INPUT_CHANGE";
export const EVENT_INPUT_CHANGE_TO_EDIT = "EVENT_INPUT_CHANGE_TO_EDIT";
export const EVENT_INPUT_CLEAN = "EVENT_INPUT_CLEAN";

export const GET_EVENTS = "GET_EVENTS";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

export const USER_INPUT_CHANGE_SUCCESS = "USER_INPUT_CHANGE_SUCCESS";
export const USER_INPUT_CHANGE_ERROR = "USER_INPUT_CHANGE_ERROR";
export const USER_INPUT_CHANGE_CLEAN = "USER_INPUT_CHANGE_CLEAN";
