export const CHANGE_SEARCH = "CHANGE_SEARCH";
export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";
export const GET_EVENTS_PENDING = "GET_EVENTS_PENDING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

export const INPUT_CHANGE_SUCCESS = "INPUT_CHANGE_SUCCESS";
export const INPUT_CHANGE_ERROR = "INPUT_CHANGE_ERROR";

export const REG_NEW_USER_SUCCESS = "REG_NEW_USER_SUCCESS";
export const REG_NEW_USER_FAILURE = "REG_NEW_USER_FAILURE";
