export const CHANGE_SEARCH = "CHANGE_SEARCH";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";
export const GET_EVENTS_PENDING = "GET_EVENTS_PENDING";
export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_FAILURE = "AUTH_USER_FAILURE";

export const INPUT_CHANGE_SUCCESS = "INPUT_CHANGE_SUCCESS";
export const INPUT_CHANGE_ERROR = "INPUT_CHANGE_ERROR";

export const REG_NEW_USER_SUCCESS = "REG_NEW_USER_SUCCESS";
export const REG_NEW_USER_FAUILURE = "REG_NEW_USER_FAUILURE";
